---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-data
  namespace: code-server
  labels:
    directory: config
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /mnt/sda/vscode
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-rspi4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      directory: config
---
