apiVersion: v1
kind: Service
metadata:
  name: code-server
spec:
  ports:
  - protocol: TCP
    port: 8443
    nodePort: 30001
  type: NodePort
  selector:
    app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: code-server
    spec:
      volumes:
      - name: code-server-data
        persistentVolumeClaim:
          claimName: code-server-claim
      containers:
      - image: linuxserver/code-server:latest
        name: code-server
        envFrom:
        - secretRef:
            name: secret-code-server
        ports:
        - containerPort: 8443
          name: code-server
        volumeMounts:
        - name: code-server-data
          mountPath: /config
